network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: true
      dhcp6: false
      dhcp4-overrides:
        use-dns: no
      nameservers:
          addresses: [1.1.1.1, 1.0.0.1]
